### ISSUE TITLE
`/quest mct1-jail stop` stops quest, but not T1D

### ISSUE THREAD

**Issue by jwulf** [Magikcraft/mct1#10]
If I type `/quest mct1-jail stop` during the jail quest, I get tp'd out of the world, but my T1 does not stop.

Do we need to put `this.player.mct1.stop()` in the base Quest class `stop()` method? And then turn it back on in each level in the `start()` method?

**Comment by triyuga** [comment]
I'm not tracking issues here. Use the Trello https://trello.com/b/ZcfRsCRg/mct1-launch-event
